name: wine-model-quality
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc pull data/winequalityN.csv
          dvc repro
          dvc push
        env:
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs

          git fetch --prune

          echo "## MODEL METRICS" > report.md
          # cat results/metrics.txt >> report.md
          dvc metrics show --md >> report.md

          echo "## AVAILABLE GPU [SELF-HOSTED]" > report.md
          CODEBLOCK="\`\`\`"
          echo $CODEBLOCK >> report.md
          nvidia-smi >> report.md
          echo $CODEBLOCK >> report.md

          echo "## Data visulization" >> report.md
          echo "![](results/fi_and_residuals.png)" >> report.md

          cml comment create report.md